cloud:
  aws:
    arn: aws:s3:::firstbucketsarthak
    credentials:
      access-key: AKIAWPZFLV6DW62YTCLE
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false


application:
  bucket:
    name: firstbucketsarthak


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9002